import Menu from "./src/Pages/Menu/Menu";
import Biriyani from './src/assets/biriyani.jpg';
import LakhnoiBiriyani from './src/assets/LakhnoiBiriyani.jpg';
import SpcBriyani from './src/assets/SpcBriyani.jpg';

export const FoodData = [
    {
        id: 1,
        MenuName: 'Biriyani',
        img: Biriyani,
        rating: "4.9",
        FoodList: [
            {
                food_id: 1,
                food_name: "Biriyani",
                tag: "Kolkata",
                time: "35 min",
                desc: "Creamy arborio rice with black truffle shavings, aged parmesan, and a drizzle of truffle oil.",
                price: "280",
                rating: "4.9",
                reviews: "214",
                badge: "Chef's Pick",
                img: Biriyani,
                featured: true,
            },
            {
                food_id: 2,
                food_name: "Biriyani",
                tag: "Kolkata",
                time: "35 min",
                desc: "Creamy arborio rice with black truffle shavings, aged parmesan, and a drizzle of truffle oil.",
                price: "280",
                rating: "4.9",
                reviews: "214",
                badge: "Chef's Pick",
                img: Biriyani,
                featured: false,
            },
            {
                food_id: 3,
                food_name: "Biriyani",
                tag: "Kolkata",
                time: "35 min",
                desc: "Creamy arborio rice with black truffle shavings, aged parmesan, and a drizzle of truffle oil.",
                price: "280",
                rating: "4.9",
                reviews: "214",
                badge: "Chef's Pick",
                img: Biriyani,
                featured: false,
            },
            {
                food_id: 4,
                food_name: "Biriyani",
                tag: "Kolkata",
                time: "35 min",
                desc: "Creamy arborio rice with black truffle shavings, aged parmesan, and a drizzle of truffle oil.",
                price: "280",
                rating: "4.9",
                reviews: "214",
                badge: "Chef's Pick",
                img: Biriyani,
                featured: false,
            },
            {
                food_id: 5,
                food_name: "Biriyani",
                tag: "Kolkata",
                time: "35 min",
                desc: "Creamy arborio rice with black truffle shavings, aged parmesan, and a drizzle of truffle oil.",
                price: "280",
                rating: "4.9",
                reviews: "214",
                badge: "Chef's Pick",
                img: Biriyani,
                featured: false,
            },
        ],
    },
];