import Biriyani from './src/assets/biriyani.jpg';
import LakhnoiBiriyani from './src/assets/LakhnoiBiriyani.jpg';
import SpcBriyani from './src/assets/SpcBriyani.jpg';
import Pizza from './src/assets/Foods/Pizza.jpg';
import Chowmin from './src/assets/Foods/Chowmin.jpg';
import Pasta from './src/assets/Foods/Pasta.jpg';
import Sweets from './src/assets/Foods/Sweets.jpg';
import Thali from './src/assets/Foods/Thali.jpg';
import Dosa from './src/assets/Foods/Dosa.jpg';


export const FoodData = [
    {
        id: 1,
        MenuName: 'Biriyani',
        FTag: 'Biriyani',
        img: Biriyani,
        desc: "Creamy arborio rice with black truffle shavings, aged parmesan, and a drizzle of truffle oil.",
        time: "35 min",
        rating: "4.9",
        reviews: "214",
        badge: "Chef's Pick",
        tag: "Kolkata",
        price: "280",
        featured: false ,
    },
    {
        id: 2,
        MenuName: 'Pizza',
        FTag: 'Pizza',
        img: Pizza,
        desc: "Creamy arborio rice with black truffle shavings, aged parmesan, and a drizzle of truffle oil.",
        time: "22 min",
        rating: "4.5",
        reviews: "2114",
        badge: "New",
        tag: "Mumbai",
        price: "320",
        featured: false,
    },
    {
        id: 3,
        MenuName: 'Chowmin',
        FTag: 'Chinese',
        img: Chowmin,
        desc: "Creamy arborio rice with black truffle shavings, aged parmesan, and a drizzle of truffle oil.",
        time: "20 min",
        rating: "4.6",
        reviews: "414",
        badge: "New",
        tag: "Mumbai",
        price: "120",
        featured: false,
    },
    {
        id: 4,
        MenuName: 'Pasta',
        FTag: 'Pasta',
        img: Pasta,
        desc: "Creamy arborio rice with black truffle shavings, aged parmesan, and a drizzle of truffle oil.",
        time: "24 min",
        rating: "4.0",
        reviews: "314",
        badge: "New",
        tag: "Mumbai",
        price: "150",
        featured: false,
    },
    {
        id: 5,
        MenuName: 'Sweets',
        FTag: 'Sweets',
        img: Sweets,
        desc: "Creamy arborio rice with black truffle shavings, aged parmesan, and a drizzle of truffle oil.",
        time: "15 min",
        rating: "4.8",
        reviews: "514",
        badge: "New",
        tag: "Mumbai",
        price: "100",
        featured: false,
    },
    {
        id: 6,
        MenuName: 'Thali',
        FTag: 'Thali',
        img: Thali,
        desc: "Creamy arborio rice with black truffle shavings, aged parmesan, and a drizzle of truffle oil.",
        time: "30 min",
        rating: "4.7",
        reviews: "214",
        badge: "New",
        tag: "Mumbai",
        price: "280",
        featured: false,
    },
    {
        id: 7,
        MenuName: 'Dosa',
        FTag: 'South Indian',
        img: Dosa,
        desc: "Creamy arborio rice with black truffle shavings, aged parmesan, and a drizzle of truffle oil.",
        time: "30 min",
        rating: "4.7",
        reviews: "214",
        badge: "New",
        tag: "Mumbai",
        price: "280",
        featured: false,
    },
];