import Biriyani from './src/assets/biriyani.jpg';
import LakhnoiBiriyani from './src/assets/LakhnoiBiriyani.jpg';
import SpcBriyani from './src/assets/SpcBriyani.jpg';
import Pizza from './src/assets/Foods/Pizza.jpg';
import Chowmin from './src/assets/Foods/Chowmin.jpg';
import Pasta from './src/assets/Foods/Pasta.jpg';
import Sweets from './src/assets/Foods/Sweets.jpg';
import Thali from './src/assets/Foods/Thali.jpg';
import Dosa from './src/assets/Foods/Dosa.jpg';
import Vada from './src/assets/Foods/Vada.jpg';
import Shakes from './src/assets/Foods/Shakes.jpg';



export const FoodData = [
    {
        id: 1,
        MenuName: 'Biriyani',
        FTag: 'Biriyani',
        img: Biriyani,
        desc: "Biryani is a spiced rice dish mixed with meat or vegetables, cooked together for rich taste and aroma.",
        time: "35 min",
        rating: "4.9",
        reviews: "4337",
        badge: "Chef's Pick",
        tag: "Kolkata",
        price: "280",
        featured: false ,
    },
    {
        id: 2,
        MenuName: 'Pizza',
        FTag: 'Pizza',
        img: Pizza,
        desc: " Pizza is a popular dish of Italian cuisine origin, consisting of a flat, round base of dough topped with ingredients like tomato sauce, cheese, and various toppings such as vegetables, meats, or herbs. It is typically baked in an oven and served hot.",
        time: "22 min",
        rating: "4.5",
        reviews: "7042",
        badge: "New",
        tag: "Mumbai",
        price: "320",
        featured: false,
    },
    {
        id: 3,
        MenuName: 'Chowmin',
        FTag: 'Chinese',
        img: Chowmin,
        desc: "Noodles are a type of food made from unleavened dough, usually prepared using wheat, rice, or other grains. The dough is rolled, stretched, or extruded into long strips or shapes and then cooked by boiling, frying, or steaming.",
        time: "20 min",
        rating: "4.6",
        reviews: "3524",
        badge: "New",
        tag: "Mumbai",
        price: "120",
        featured: false,
    },
    {
        id: 4,
        MenuName: 'Pasta',
        FTag: 'Pasta',
        img: Pasta,
        desc: "Pasta is a staple food of Italian cuisine made from a dough of wheat flour mixed with water or eggs. It is shaped into various forms like spaghetti, penne, or macaroni and then boiled before serving.",
        time: "24 min",
        rating: "4.0",
        reviews: "3685",
        badge: "New",
        tag: "Mumbai",
        price: "150",
        featured: false,
    },
    {
        id: 5,
        MenuName: 'Sweets',
        FTag: 'Sweets',
        img: Sweets,
        desc: "A sweet is a type of food that has a sugary taste and is usually served as a dessert or snack. It is made using ingredients like sugar, milk, flour, chocolate, or fruits.",
        time: "15 min",
        rating: "4.8",
        reviews: "9778",
        badge: "New",
        tag: "Mumbai",
        price: "100",
        featured: false,
    },
    {
        id: 6,
        MenuName: 'Thali',
        FTag: 'Thali',
        img: Thali,
        desc: "A typical veg thali may contain items like roti or rice, dal, different vegetable curries, curd, pickle, salad, and a sweet dish. It offers a complete and balanced meal with different flavors.",
        time: "30 min",
        rating: "4.7",
        reviews: "12457",
        badge: "New",
        tag: "Mumbai",
        price: "280",
        featured: false,
    },
    {
        id: 7,
        MenuName: 'Dosa',
        FTag: 'South Indian',
        img: Dosa,
        desc: "Dosa is a traditional dish from South Indian cuisine made from a fermented batter of rice and urad dal (black gram). It is cooked as a thin, crispy pancake on a hot griddle.",
        time: "30 min",
        rating: "4.7",
        reviews: "2014",
        badge: "New",
        tag: "Mumbai",
        price: "280",
        featured: false,
    },
    {
        id: 8,
        MenuName: 'Vada',
        FTag: 'South Indian',
        img: Vada,
        desc: "Vada is a popular savory snack from South Indian cuisine made from a batter of lentils (usually urad dal) or potatoes. It is shaped into small rounds or rings and deep-fried until crispy.",
        time: "30 min",
        rating: "4.7",
        reviews: "2587",
        badge: "New",
        tag: "Mumbai",
        price: "280",
        featured: false,
    },
    {
        id: 9,
        MenuName: 'Shakes',
        FTag: 'Shakes',
        img: Shakes,
        desc: "Shakes (or milkshakes) are cold beverages made by blending milk with ingredients like ice cream, fruits, chocolate, or flavored syrups until smooth and creamy.",
        time: "30 min",
        rating: "4.7",
        reviews: "3654",
        badge: "New",
        tag: "Mumbai",
        price: "280",
        featured: false,
    },
];